### ISSUE TITLE
[Bug] Phone sometimes not charging

### ISSUE THREAD

**Issue by XXXBold** [sriharshaarangi/BatteryChargeLimit#133]
Device: Galaxy S5 SM-G900-F
OS: LineageOS 15.1 with root (Android 8.1, no GApps)
App Version: 1.1.0 (Current from F-Droid store)

App Configuration:
Keep charged between 93-95%, no notification. In settings: I tried Force Limit enabled/disabled, but the bugs seem to happen anyway.
control file is batt_slate_mode (selected by default)

Problems:
1) Sometimes, when plugging in the phone, it doesn't start charging, even if it's (far) below 93%. I see the BatteryChargeLimit app is showing up in the statusbar, which says "Wait for 95%" and there's also the lightning (charge indicator) in the battery icon on the statusbar, but actually it's not charging, and the charging light is also off. I need to restart the phone then, to make charging work again. If I open the app in this case and check the status, it says: "Status: KEIN LADEN" (It's on German, means no charging) and /sys/.../batt_slate_mode,0,1.
2) Sometimes when I try to open the app, it crashes.

**Comment by milux** [comment]
Logcat please! 😄

**Comment by XXXBold** [comment]
I got the bug again, here's the log extracted using the app "logCat Reader", there was an exception a few times in your app, hope this helps you (The date is different for the logs), I've put it on pastebin, if you need more/other informations, let me know ;).

http://pastebin.de/7661/

**Comment by milux** [comment]
Ahm... sorry, but your pastebin link is a 404 :(

**Comment by XXXBold** [comment]
Uhh damn, guess it was deleted.. anyway, I'll put it here then:

`[10-02 19:46:21.824 13096:13096 F/DEBUG]
pid: 1969, tid: 2117, name: RenderThread  >>> com.slash.batterychargelimit <<<

[10-02 19:46:24.303 13103:13103 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.slash.batterychargelimit, PID: 13103
java.lang.RuntimeException: Unable to start service com.slash.batterychargelimit.ForegroundService@8a3c68f with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3491)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at com.slash.batterychargelimit.ForegroundService.onStartCommand(Unknown Source:2)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
	... 8 more

[10-02 20:14:00.876 20283:20283 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.slash.batterychargelimit, PID: 20283
java.lang.RuntimeException: Unable to start service com.slash.batterychargelimit.ForegroundService@d5ecf41 with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3491)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at com.slash.batterychargelimit.ForegroundService.onStartCommand(Unknown Source:2)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
	... 8 more
	
[10-04 11:50:58.229 480:570 I/chatty]
uid=1000(system) batterystats-wo expire 3 lines

[10-04 22:59:29.497 10941:10941 F/DEBUG]
pid: 10831, tid: 10912, name: RenderThread  >>> com.slash.batterychargelimit <<<

[10-04 22:59:31.857 10948:10948 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.slash.batterychargelimit, PID: 10948
java.lang.RuntimeException: Unable to start service com.slash.batterychargelimit.ForegroundService@8a3c68f with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3491)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at com.slash.batterychargelimit.ForegroundService.onStartCommand(Unknown Source:2)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
	... 8 more

[10-05 04:55:54.579 4841:4841 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.slash.batterychargelimit, PID: 4841
java.lang.RuntimeException: Unable to start service com.slash.batterychargelimit.ForegroundService@8a3c68f with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3491)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at com.slash.batterychargelimit.ForegroundService.onStartCommand(Unknown Source:2)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
	... 8 more
	
[10-05 07:21:02.071 9535:9535 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.slash.batterychargelimit, PID: 9535
java.lang.RuntimeException: Unable to start service com.slash.batterychargelimit.ForegroundService@1781f08 with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3491)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.slash.batterychargelimit.ForegroundService.onStartCommand, parameter intent
	at com.slash.batterychargelimit.ForegroundService.onStartCommand(Unknown Source:2)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
	... 8 more
	
[10-06 18:59:06.644 480:570 E/BatteryExternalStatsWorker]
no controller energy info supplied for wifi

[10-06 19:07:21.448 480:570 E/BatteryExternalStatsWorker]
no controller energy info supplied for bluetooth

[10-06 19:07:21.464 480:570 E/BatteryExternalStatsWorker]
modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}

[10-06 23:13:59.155 480:480 I/ActivityManager]
Killing 20268:com.slash.batterychargelimit/u0a90 (adj 906): empty for 24646s

[10-07 10:13:31.891 480:558 D/BatteryStatsImpl]
Reading cpu stats took 179 ms

[10-07 10:48:39.095 480:558 I/ActivityManager]
Start proc 10089:com.slash.batterychargelimit/u0a90 for broadcast com.slash.batterychargelimit/.receivers.PowerConnectionReceiver

[10-07 10:48:39.730 10187:10187 D/su]
Checking whether app [uid:10090, pkgName: com.slash.batterychargelimit] is allowed to be root

[10-07 10:48:40.275 10089:10224 I/chatty]
uid=10090(com.slash.batterychargelimit) RenderThread expire 10 lines

`

Not sure if these are all logs from your app, though.

Some of the entries appear very often, more than i posted here, like the "[10-04 11:50:58.229 480:570 I/chatty]
uid=1000(system) batterystats-wo expire 3 lines" with diffrent line numbers. But anyway, hope these logs will help you :)

**Comment by milux** [comment]
Are you using an outdated version?
From what I can see, this error comes from a bug that was fixed on the 23rd of April this year by @angelsl 😕

**Comment by XXXBold** [comment]
As I wrote at the beginning, I'm using v 1.1.0, the current from F-Droid Store, released 16.02.18. I don't find an update there.

**Comment by milux** [comment]
I found the problem... the F-Droid version is far behind (January), because we didn't push a new tag when we bumped the version to 1.1.1 in May...
@sriharshaarangi I'll create this tag now so F-Droid can get 1.1.1.

**Comment by milux** [comment]
@XXXBold Version 1.1.1 without this bug should be available on F-Droid soon, closing this now.
